specVersion: 0.2.0
name: subql-crab-nft
version: 0.0.4
description: Crab Plo NFT claim address remark
repository: https://github.com/darwinia-network/subql-crab-nft.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 11415420
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSystemRemarkCall
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
